services:
  - type: web
    name: telegram-dice-bot
    runtime: python
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value:  7903716016:AAGkz66p120DpM0z_zMuAKwtIpvuMubZRI4
      - key: DEPLOYMENT_MODE
        value: webhook
      - key: WEBHOOK_URL
        value: https://dicee-sl0r.onrender.com
      - key: PORT
        value: 10000
